Setuped Repo
WSB-CW8/Co-Development-Task pull request #7
Opened 2024-10-20 12:37 UTC by AstralJacob

2024-10-20 13:54 UTC, Kinggred requested changes

2024-10-20 13:54 UTC, Kinggred commented on .idea/.gitignore
Please add .idea to `.gitignore`.
Don't remove it thought,.

2024-10-20 14:01 UTC, AstralJacob commented on .idea/.gitignore
done

2024-10-20 14:06 UTC, Kinggred approved these changes

2024-10-20 14:08 UTC, merged

2024-10-30 17:01 UTC, akucinskii commented
resolves #33